### ISSUE TITLE
Unit tests for models fails on Windows in Post-Merge Checks

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#373]
Update on 11 Aug - this proposed fix also failed on HRnet test after an update to markdowns that is unrelated. We are assuming that bug has something to do with Windows server and ML models and are removing Windows testing for post merge tests while keeping in pre merge tests.

**Issue:**
- Yolo unit test failing on Github actions in post merge check
- The error does not occur when running on Windows 10 locally, but happens when using Windows Server 2019 or 2016 on Github actions: https://github.com/aimakerspace/PeekingDuck/runs/3215195661?check_suite_focus=true
- No error when running Ubuntu
- Log when enabling cli logging for pytest and adding log messages to yolo unit test script:
![image](https://user-images.githubusercontent.com/33995028/127975884-e3326121-ea99-4a9c-bdc6-3fd16fb4bfde.png)

**Root cause:**
- The unit test for yolo runs inference on 5 test images via two methods.
-  Established that the error will occur upon running yolo on the 3rd image, with no issues on the first 2 images. This can be seen in the screenshot above.
- It's very peculiar because efficientdet does a similar test on the same 5 images, and it's a much heavier model than yolo, without issues
- Googling of `Windows fatal exception: access violation` suggests that it may be caused by incompatibility between this version of Windows Server and Python/TF/numpy etc. Tried a few combinations of package versions but error persisted.

**Proposed solution:**
- Limit yolo unit test to 2 images, while keeping 5 images for other tests and keeping Windows OS testing on post-merge checks
- Continue monitoring this for future models

**Comment by liyier90** [comment]
This turned out to be a combination of issues:
1. `pytest` fixture does not attempt to free memory after yielding each image
2. `pyest` keeps fixtures alive to report warnings at the end of the suite. Relevant issue: https://github.com/pytest-dev/pytest/issues/5642#issuecomment-513999531
3. General behavior of running a large suite, test report is stored in memory and only printed at the end. Relevant [SO](https://stackoverflow.com/a/20934950).

A potential solution is to run each of the tests marked as `mlmodel` iteratively and [combine the coverage](https://stackoverflow.com/questions/22075933/how-to-get-combined-code-coverage-over-multiple-runs-of-python-script).
