### ISSUE TITLE
Windows: Step-by-step test RTD & readme

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#377]

**Comment by ongzizhao** [comment]
I have noticed some errors in the RTD guide and also some areas that require more clarification for the benefit of readers.

In the Getting Started > Changing Nodes and Settings > Configuring node behaviour > via CLI section:
- The guide suggested `input.live  : {'input_dir': <directory where videos/images are stored}`. 
- Input live node do not have input dir argument. should be replaced with input.recorded. 
- Also for the directory/filepath need to high light to be in apostrophe `  {'input.recorded'  : {'input_dir': '<directory where videos/images are stored>'}}`
- When testing in windows need to suggest to use `\\` rather than single `\` in the filepath 
- The example run_config.yml did not use output.media_writer but the `--node_config` example used it 
- Should highlight that updates using `--node_config` in CLI can only update configs for nodes declared in run_config.yml

In the Getting Started >Building Custom Nodes to run with PeekingDuck>Step 3: Create Node Configs section:
- the file path for the `<node>.yml` example should use `filepath: '<filepath>.csv' ` as the user may not have created a `<results>` file dir
- using `filepath: 'results/stats.csv' ` without creating `<results>` file dir will raise a file do not exist error

In the Getting Started >PeekingDuck Python API>Sample Code section:
- similiar to the above issue raise, `input_node = recorded.Node(input_dir="data/input/t1.jpg")` and `output_node = media_writer.Node(output_dir="data/output")` should state `input_node = recorded.Node(input_dir="<file path>")` and `output_node = media_writer.Node(output_dir="<filepath>")`
- so as to avoid any error due to filepath to not exist if user copy the code as it is in the guide
