### ISSUE TITLE
Video threading for Linux

### ISSUE THREAD

**Issue by leeping-ng** [aimakerspace/PeekingDuck#432]
#427's solution 3 was implemented, which turns off threading by default, causing a 25% performance hit. 

We could possibly moving threading to the runner and enable it to work.

Another option is to check the OS in the module and enable threading if Win or MacOS

**Comment by ongtw** [comment]
Pushed branch 432_threading_feature to support threading (for input nodes) on Windows, MacOS and Linux.

Fixed issues with existing code:

1. In `VideoThread` class: `__del__()` is not a destructor and cannot be depended for resource cleanup as whether it gets called is non-deterministic. For more info, see [https://stackoverflow.com/questions/40536821/python-enter-exit-vs-init-or-new-del](url).
2. Because of 1, webcam acquired by opencv was never properly released. The segfault on Linux is due to this. Windows and MacOS seem more forgiving towards this issue.
3. To ensure proper resource cleanup, added `shutdown()` method to `VideoThread`. `thread.join()` is executed here.
4. Thread communication is done using `Event` object. `VideoThread`'s `self.done` event object is set to indicate end of threading.
5. Added 3 second delay in `__init__` to give time for thread to start and for camera to be initialised, else pipeline will end prematurely before camera can capture any images.
6. Also added `release_resources()` method to `Node` class, to be overridden as required. `input.live` and `input.recorded` override this method to call `shutdown()` on `self.videocap`.
7. Finally, `Runner` class `run()` method needs to perform a clean up after `pipeline.terminate` by iterating through all nodes and calling `node.release_resources()` as appropriate. 
8. Added platform check for Windows and call `cv2.VideoCapture` with `cv2.CAP_DSHOW` flag to prevent opencv's `[WARN] terminating async callback` message upon exit.
9. Upgraded `input.recorded` to support threading also. Requires `VideoThread` to include `fps` and `frame_count` properties.

Tested `live` and `recorded` on macOS Big Sur, Windows 10 and Ubuntu 20.04, both threaded and non-threaded.
(Unfortunately, `recorded` is now throwing pathname errors on Windows due to the `/` and `\` conflicts.)

**Comment by ongtw** [comment]
Fixed `recorded` path errors on Windows

**Comment by ongtw** [comment]
Shifted development work to https://github.com/ongtw/PeekingDuck/tree/432_threading_feature

**Comment by leeping-ng** [comment]
PR #523 has been merged to resolve this issue.
