### ISSUE TITLE
Add wildcard to object detection models to allow all classes to be detected

### ISSUE THREAD

**Issue by chngzyk** [aimakerspace/PeekingDuck#486]

**Comment by liyier90** [comment]
Possible to detect all classes by default if no ID is passed in (`detect_ids = []`)?

**Comment by ongtw** [comment]
Possible "wildcard" implementation options in `run_config.yml`:
1. `detect_ids: []`
2. `detect_ids: [*]`
3. `detect_ids: all` (or `any`)
4. `detect_ids: *`

Any suggestions for which of the above should be supported? Or support all of the above?

**Comment by liyier90** [comment]
I prefer options 1 and 2 since they looks most similar to `detect_ids` is normally used. Maybe less chance of errors like doing `detect_ids: person, airplane` when switching from wildcard to specific classes.

Another consideration is how the actual "detect all classes" is implement:
a. Translate the above to a list of 80 class IDs
b. Skipping the "filter by class" step in each of the model files.

Personally I prefer Option b since it's probably less computationally expensive although implementing that for all models might take some effort.

For example in [`yolo`](https://github.com/aimakerspace/PeekingDuck/blob/node-v1.2/peekingduck/pipeline/nodes/model/yolov4/yolo_files/detector.py#L103-L106), Option a will probably result in 4 redundant operations.

If going with Option b, then supporting Option 1 will be the most straight forward. If not, then probably can support both Options 1 and 2 based on the "similar looks" as mentioned in the beginning.

**Comment by ongtw** [comment]
Ok, will implement 2. I think 1 can give the impression that it means "detect nothing" since the list is empty. 2 is more intuitive as * is often used as wildcard to mean all.

Good point on the implementation. My initial idea was to do it the simple way of a), which will have the benefit of not modifying the models in anyway, albeit at the expense of runtime performance.
If we have time (and reason) to do b), then it will be a better option, though it would mean more resources for implementation and testing.

**Comment by ongtw** [comment]
Update: To implement the simple method a)
- Safer direction as "under-the-hood" model code is not modified.
- The bulk of inference time should be spent on model computation; object id filtering should not incur significant runtime penalty.
- To benchmark and verify above assumption.

**Comment by ongtw** [comment]
Technotes:
1. Yaml syntax needs to be `detect_ids: ["*"]` as `*` is a special character that needs to be quoted.
2. If `detect_ids: []`, then default to `detect_ids: [person]` and display warning to inform user that an empty list is detected and PKD is defaulting to detecting person.

**Comment by ongtw** [comment]
`make html` in `docs/` is giving the following warnings:
``` make
❯ make html
Running Sphinx v4.3.2
loading pickled environment... done
myst v0.16.1: MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['dollarmath'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['http', 'https', 'mailto', 'ftp'], heading_anchors=2, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
[autosummary] generating autosummary for: getting_started/01_installation.md, getting_started/02_configure_pkdk.md, getting_started/03_custom_nodes.md, getting_started/04_import_peekingduck.md, getting_started/index.rst, index.md, master.rst, peekingduck.cli.create_custom_folder.rst, peekingduck.cli.create_yml.rst, peekingduck.cli.rst, ..., use_cases/face_mask_detection.md, use_cases/group_size_checking.md, use_cases/human_tracking.md, use_cases/index.rst, use_cases/multi_object_tracking.md, use_cases/object_counting.md, use_cases/privacy_protection_faces.md, use_cases/privacy_protection_license_plate.md, use_cases/social_distancing.md, use_cases/zone_counting.md
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 3 changed, 0 removed
reading sources... [100%] peekingduck.configloader.ConfigLoader                                                                               
/Users/dotw/src/ongtw/PeekingDuck/docs/source/peekingduck.configloader.ConfigLoader.rst:96: WARNING: Error in "rubric" directive:
no content permitted.

.. rubric:: Methods


   ~ConfigLoader.change_class_name_to_id
   ~ConfigLoader.get
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/dotw/src/ongtw/PeekingDuck/docs/source/use_cases/human_tracking.md: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] peekingduck.configloader.ConfigLoader                                                                                
generating indices... genindex py-modindex done
highlighting module code... [100%] peekingduck.weights_utils.finder                                                                           
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 2 warnings.
```

**Comment by liyier90** [comment]
`human_tracking.md` was not added to `use_cases/index.rst`, I missed that during the review. I can add it to the refactor PR I'm working on. I think the rubric warning is "normal" since I think it's set to only show the class docstring with the config options.

I think the missing GIFs are also "normal" because they reference the actual URLs when node-v1.2 becomes "stable".

**Comment by liyier90** [comment]
For example, this is one of the warnings I get when building the docs from scratch:
```
/home/yier/code/PeekingDuck/docs/source/peekingduck.pipeline.nodes.output.csv_writer.Node.rst:96: WARNING: Error in "rubric" directive:
no content permitted.

.. rubric:: Methods


   ~Node.load_node_config
   ~Node.release_resources
   ~Node.run
```
